# =============================================================================
# GitHub Actions — Terraform Plan on PR, Apply on Merge
# =============================================================================
# Security rules:
# - Secrets via GitHub Secrets → TF_VAR_ environment variables
# - Plan runs on every PR (read-only, safe)
# - Apply runs ONLY on merge to main (destructive, gated)
# - Uses -input=false to prevent interactive prompts
# - Uses -no-color for clean log output

name: Terraform

on:
  pull_request:
    paths:
      - "infra/**"
  push:
    branches:
      - main
    paths:
      - "infra/**"

env:
  TF_VERSION: "1.5"
  WORKING_DIR: "infra/discord"

jobs:
  # ===========================================================================
  # Plan — runs on every PR
  # ===========================================================================
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform plan -input=false -no-color
        env:
          TF_VAR_discord_token: ${{ secrets.DISCORD_BOT_TOKEN }}

  # ===========================================================================
  # Apply — runs ONLY on merge to main
  # ===========================================================================
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    environment: production  # Requires manual approval in GitHub

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init -input=false

      - name: Terraform Apply
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform apply -input=false -auto-approve -no-color
        env:
          TF_VAR_discord_token: ${{ secrets.DISCORD_BOT_TOKEN }}
