# Renderable artifact job template: detect-render-bundle pattern.
#
# Use this pattern for any source files that need compilation/rendering
# into output artifacts (PDF, SVG, generated code, etc.).
#
# The pattern has 2 jobs:
#   1. Render job (matrix) — compiles/renders each changed file individually
#   2. Bundle job          — merges individual artifacts into a single download
#
# Prerequisites:
#   - The `affected` job must output a JSON array of changed files
#     (e.g., `changed-tex`, `changed-mmd`, `changed-proto`)
#   - The `affected` job must output a project-level boolean
#     (e.g., `latex`, `diagrams`)
#
# To adapt for a new renderable type:
#   1. Replace the `if:` conditions with your project key + changed-files output
#   2. Replace the matrix key name and source
#   3. Replace the render step with your compilation command
#   4. Adjust artifact names and paths

# --- Example: Mermaid diagram rendering ---

jobs:
  # Job 1: Render each changed file individually
  build-diagrams:
    name: Build diagram ${{ matrix.mmd }}
    needs: affected
    # Gate on BOTH: project was affected AND there are actual files to render
    if: needs.affected.outputs.diagrams == 'true' && needs.affected.outputs.changed-mmd != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Don't cancel other renders if one fails
      matrix:
        mmd: ${{ fromJson(needs.affected.outputs.changed-mmd) }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Render ${{ matrix.mmd }}
        run: |
          MMD="${{ matrix.mmd }}"
          SVG="${MMD%.mmd}.svg"
          NAME=$(basename "$SVG")
          mkdir -p output
          echo "Rendering: $MMD -> $SVG"
          ./node_modules/.bin/mmdc -i "$MMD" -o "output/$NAME" -b transparent -p puppeteer-config.json

      # Upload with short retention (temporary, will be merged in bundle)
      - name: Upload SVG
        uses: actions/upload-artifact@v4
        with:
          name: svg-${{ hashFiles(matrix.mmd) }}
          path: output/*.svg
          retention-days: 1

  # Job 2: Merge individual artifacts into a single bundle
  bundle-diagrams:
    name: Bundle SVGs
    needs: build-diagrams
    # Run even if some renders failed, but not if the whole job was skipped
    if: always() && needs.build-diagrams.result != 'skipped'
    runs-on: ubuntu-latest
    steps:
      - name: Download all SVGs
        uses: actions/download-artifact@v4
        with:
          pattern: svg-*
          merge-multiple: true
          path: output

      # Upload the merged bundle with longer retention
      - name: Upload SVG bundle
        uses: actions/upload-artifact@v4
        with:
          name: bastet-diagrams
          path: output/*.svg
          retention-days: 30

      # Clean up the temporary individual artifacts
      - name: Clean up individual artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: svg-*
